### ISSUE TITLE
Incrementar Sistema de Log

### ISSUE THREAD

**Issue by TomazMartins** [Scarefault/Management-Central#24]
### Lista de Tarefas

- [x] Arrumar o Erro de formatação da saída: aparecem caracteres desconhecidos, entre a mensagem e a data. Isso não ocorria antes.
- [x] Arrumar o horário impresso: esse horário não está correspondendo com o horário corrente, em relação às horas. Minutos e segundos estão corretos.
- [x] Gerar outros tipos de mensagem, como `error( )`, `warning( )` e `success( )`.

**Comment by Thaiane** [comment]
O horário está sendo impresso corretamente. O que estava acontecendo é que a função pega o horário local da máquina. Se o Scarefault for executado na sua máquina funciona no horário do Brasil. Se for executado na máquina virtual funciona com o horário do país da VM, acho que os Estados Unidos.
