### ISSUE TITLE
Identificação de Elementos de Atribuição de Variáveis

### ISSUE THREAD

**Issue by Thaiane** [Scarefault/Management-Central#3]
## História de Usuário
*Eu, como desenvolvedor, quero identificar os elementos de atribuição de variáveis, para análises futuras desses elementos.*

## Critérios de Aceitação
- [ ] Identificar de atribuição de valores do tipo *strings*, caracteres, números (inteiros e ponto flutuante), *arrays* e de tipos definidos pelos usuários.

**Comment by Thaiane** [comment]
É necessário que haja alterações para identificação de números negativos. Além disso, uma revisão conceitual sobre atribuições e declarações de variáveis em *Grails*.

**Comment by TomazMartins** [comment]
Certo!
